/**
 * Root Layout Component
 * 
 * This is the top-level layout component in a Next.js application.
 * It wraps all pages and provides common elements that should appear
 * on every page throughout the application.
 */
import './globals.css'
// Metadata definition for the application - used by Next.js for SEO and browser display
export const metadata = {
  title: 'Next.js',               // Sets the title shown in browser tabs and search results
  description: 'Generated by Next.js',  // Provides a description for search engines
}

/**
 * RootLayout Component
 * 
 * This function serves as the base layout template for the entire application.
 * It wraps all page content within proper HTML structure including html and body tags.
 * 
 * @param {Object} props - Component properties
 * @param {React.ReactNode} props.children - Child components (page content) to render within the layout
 * @returns {JSX.Element} The complete HTML document structure
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // Root HTML element with language attribute for accessibility
    <html lang="en">
      {/* Body element containing all page-specific content */}
      <body>{children}</body>
    </html>
  )
}
