import { expect, test, describe } from 'vitest';
import { render, screen } from '@testing-library/react';
import RootLayout from './layout';
import { metadata } from './layout';

describe('RootLayout', () => {
    test('renders children properly', () => {
        const testContent = 'Test child content';
        const { container } = render(
            <RootLayout>
                <div>{testContent}</div>
            </RootLayout>
        );
        
        expect(container.textContent).toContain(testContent);
    });


    test('body element contains the children', () => {
        render(
            <RootLayout>
                <span data-testid="test-child">Specific child</span>
            </RootLayout>
        );
        
        // Fix: Use screen.getByTestId to find the element
        const childElement = screen.getByTestId('test-child');
        expect(childElement).toBeInTheDocument();
        expect(childElement.textContent).toBe('Specific child');
    });

    test('metadata has correct values', () => {
        expect(metadata).toEqual({
            title: 'Next.js',
            description: 'Generated by Next.js'
        });
    });

    test('renders with multiple children', () => {
        const { container } = render(
            <RootLayout>
                <div>First child</div>
                <div>Second child</div>
            </RootLayout>
        );
        
        expect(container.textContent).toContain('First child');
        expect(container.textContent).toContain('Second child');
    });
});